name: Test project
on:
  push:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
      - uses: ajrly/gh-workflow-template/.github/actions/pnpm-install@main
      - name: Linting
        run: pnpm lint
      - name: Building
        run: pnpm build
      - name: Testing
        run: pnpm test:coverage
